spring:
  session:
    timeout: 86400 # session过期时间，一天失效

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: 123456
    url: jdbc:mysql://121.199.29.155:3306/user_center # 线上数据库地址