spring:
  application:
    name: user-center
  session:
    timeout: 86400 # session过期时间，一天失效

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ucenter

server:
  port: 8080
  servlet:
    context-path: /api

# 输出 SQL 日志
logging:
  level:
    com:
      lianyu:
        usercenter:
          mapper: debug  # 设置 MyBatis Mapper 接口的日志级别为 debug
    org:
      mybatis: debug    # 设置 MyBatis 核心日志级别为 debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
